### ISSUE TITLE
'gatsby develop' leads to ReferenceError

### ISSUE THREAD

**Issue by adrien-perello** [mathieudutour/gatsby-digital-garden#134]
# Problem

I can't develop the site with the theme

# Manipulation

I tried both with Gatsby CLI
> ```gatsby new dg https://github.com/mathieudutour/gatsby-starter-digital-garden```

AND manually changing the theme after installation of gatsby-theme-blog (from the [tutorial](https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/using-a-gatsby-theme/) mentioned on this github page)

In both case I get **```ReferenceError: Join is not defined```**

![Screenshot from 2021-07-08 15-41-09](https://user-images.githubusercontent.com/76055749/124932921-c1731300-e003-11eb-9219-c6498f256984.png)

# Other tests

I precise that i install a new site using gatsby CLI with
- gatsby-theme-blog
- [gatsby-garden](https://github.com/binnyva/gatsby-garden)

**and those 2 themes worked**

What am I missing? Anyone else encounter the same problem?

**Comment by mathieudutour** [comment]
ah sorry, should be fixed if you reinstall the dependencies now
