### ISSUE TITLE
'gatsby develop' leads to compilation fail

### ISSUE THREAD

**Issue by adrien-perello** [mathieudutour/gatsby-digital-garden#135]
# Problem

problem with graphql after ```gatsby develop``` (probably related to #134)

I get this
![Screenshot from 2021-07-08 17-50-43](https://user-images.githubusercontent.com/76055749/124953480-7c57dc80-e015-11eb-904e-5dc8d8158253.png)

and http://localhost:8000/ gives this
![Screenshot from 2021-07-08 17-53-07](https://user-images.githubusercontent.com/76055749/124953475-7b26af80-e015-11eb-8965-f50e07af33ec.png)

Does it also have to do with dependencies? Or is the problem coming from my machine?

**Comment by mathieudutour** [comment]
what version are you using?

**Comment by adrien-perello** [comment]
node: 14.17.1
npm: 6.14.13
gatsby-cli: 3.9.0

**Comment by mathieudutour** [comment]
I mean which version of `gatsby-digital-garden`? But I'm not sure it is compatible with Gatsby version 3

**Comment by adrien-perello** [comment]
in ```package.json``` I see:
```
"dependencies": {
    "gatsby": "^2.21.37",
    "gatsby-theme-garden": "^0.1.1",
```
But to be honest, I simply did
> ```gatsby new my-digital-garden https://github.com/mathieudutour/gatsby-starter-digital-garden```

Do i have to downgrade gatsby-cli to version 2?

**Comment by adrien-perello** [comment]
This is not working. I uninstall, reinstall, try several times. And what seems to work is to do a 'dummy' git commit before ```gatsby develop```
