### ISSUE TITLE
How to change theme colors

### ISSUE THREAD

**Issue by aadimator** [mathieudutour/gatsby-digital-garden#138]
First of all, thanks a bunch for providing us with such an amazing resource/theme. Much much appreciated. 

Sorry if this is a very trivial thing to do but I have very little experience with Gatsby.  Is there a way to update the theme colors without modifying the actual `gatsby-theme-garden\src\components\themes.css` file? I want to be able to define my own colors in a CSS file that overrides the default theme colors. 

Thanks.

**Comment by mathieudutour** [comment]
You can use the theme override feature from Gatsby and create a file called `src/gatsby-theme-garden/components/custom.css` and put any css you want there (including overwriting the css variables from the theme)
