### ISSUE TITLE
Long (tall) pages cause header to shrink

### ISSUE THREAD

**Issue by keikhcheung** [mathieudutour/gatsby-digital-garden#16]
When a note page is longer than the viewport height, it causes the header bar at the top the shrink slightly.

Full height
![Full height header](https://user-images.githubusercontent.com/22561336/84959524-c8c93500-b0ff-11ea-809a-2e82338720bc.png)

Shrunk
![Shrunk header](https://user-images.githubusercontent.com/22561336/84959560-dc749b80-b0ff-11ea-8e98-448fcbc45021.png)

The problem is more obvious when jumping from a page where scrolling is not necessary to one where scrolling is needed.

**Comment by mathieudutour** [comment]
Should be fixed in 0.1.5
