### ISSUE TITLE
Automatic jumping to the top on long (tall) pages

### ISSUE THREAD

**Issue by keikhcheung** [mathieudutour/gatsby-digital-garden#17]
When there are more than 1 page open, and after scrolling a bit down on a long (tall) active page:

- Panning horizontally causes this active long (tall) page jump to the very top; and
- Hovering over any reference link under 'Referred in' at the bottom of this page causes the same problem—jumping to the top of this long (tall) page.

**Comment by mathieudutour** [comment]
Should be fixed in 0.1.5
