### ISSUE TITLE
The internal links do not work in the example site https://mathieudutour.github.io/gatsby-digital-garden/

### ISSUE THREAD

**Issue by saurabhkarmakar** [mathieudutour/gatsby-digital-garden#19]
Clicking any of the internal links, example [[React]] opens up a blank page. I have tried it on Chrome Version 83.0.4103.116 (Official Build) (64-bit) and Safari Version 13.1 (15609.1.20.111.8).

**Comment by mathieudutour** [comment]
Ah thanks for the report. Should be fixed in 0.1.8 (and the example is fixed)
