### ISSUE TITLE
Support for space in file name

### ISSUE THREAD

**Issue by saurabhkarmakar** [mathieudutour/gatsby-digital-garden#20]
I performed the following experiment. I followed your instructions and created a Gatsby site. I then copied two markdown files to the content/garden folder:
* How to Win Supporters and Influence Detractors.md
* sites-inspired.md

Now, from the hello.mdx file, I created four links:

1. [[How to Win Supporters and Influence Detractors]]
2. [[sites-inspired]]
3. [[sites inspired]]
4. [[Sites Inspired]]

My observation:
Link 1 does not work, displays Gatsby.js development 404 page. (Page it looks for: /How-to-Win-Supporters-and-Influence-Detractors.md)
Link 2 and 3 works. (Page both look for /sites-inspired.md)
Link 4 does not work, shows a blank white page. (Page it looks for: /Sites-Inspired.md)

My suggestion, while generating the static site pages:

1. Covert white spaces to dashes
2. Only use small letters

**Comment by mathieudutour** [comment]
So it does work with spaces in the file name - but what you reference in `[[...]]` is the **title** of the file which either the title field in the frontmatter section or the first  h1 header. The fact that it works for Link 2 and 3 is just a coincidence.

Keep in mind that some file system are case sensisive (eg. you can have both `site-inspired.md` and `Sites-Inspired.md`)

**Comment by saurabhkarmakar** [comment]
Per your suggestion, I tried first by adding title in the front matter section.

---
title: How to Win Supporters and Influence Detractors
---

The link did not work. Is there any other way of adding title in frontmatter that will make the link work?

Then I removed the title and tried the first h1 header.

# How to Win Supporters and Influence Detractors

The link started working. Ditto with Link 4.

Thanks.

**Comment by loikein** [comment]
Hi, I wonder is it possible to use the file names as reference id (inside `[[…]]`)? 
I want to try out this package, but my backlog were generated _not_ with RoamResearch, so all the links do not work now.

**Comment by mathieudutour** [comment]
Normal markdown links should work. How did you generate your files?

**Comment by loikein** [comment]
I am using a markdown editor called Obsidian, which supports [[]] links to file name & titles inside files. 

I have tried to do the following modification to [gatsby-digital-garden/on-create-node.ts](https://github.com/mathieudutour/gatsby-digital-garden/blob/master/packages/gatsby-transformer-markdown-references/src/on-create-node.ts), but the site won't show anything when `gatsby develop`…

```js
const path = require('path');
function getTitle(node, content) {
    if (typeof node.frontmatter === "object" &&
        node.frontmatter &&
        markdown_utils_1.findTopLevelHeading(content)) {
        // @ts-ignore
        return markdown_utils_1.findTopLevelHeading(content);
    }
    return node.parent.filename || "";
}
```

**Comment by mathieudutour** [comment]
I published a new version, can you let me know if it works?

**Comment by loikein** [comment]
Oh my word, yes! Thank you so much!
