### ISSUE TITLE
Warnings for many deprecated packages on creating new gatsby-digital-garden site

### ISSUE THREAD

**Issue by nixsee** [mathieudutour/gatsby-digital-garden#26]
I'm new to Gatsby, so odds are that I've messed something up. But I first installed the default starter site without issue.

When installing gatsby-digital-garden, I receive many warnings about deprecated packages. Is it because I installed Node.js 14 instead of the LTS 12? Will this cause problems?

npm WARN deprecated @hapi/joi@15.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated graphql-import@0.7.1: GraphQL Import has been deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-import for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.
npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

**Comment by nixsee** [comment]
Nevermind. I replaced it with 12 and seems to be working now.

**Comment by nixsee** [comment]
Though, now that I think of it, what would be involved in bringing this up to date? v14 will be the main active version in October.

**Comment by mathieudutour** [comment]
That's an issue to open in the Gatsby repo, all the warnings come from there. The dependencies of this theme are up to date.
