### ISSUE TITLE
Idea: Handle embeds

### ISSUE THREAD

**Issue by synesthesia** [mathieudutour/gatsby-digital-garden#27]
I'm in the middle of porting my evergreen notes from Federated Wiki to Foam, and realised that I needed to have the ability to embed things like YouTube videos for some posts.

Although I'm now working on publishing via a custom gatsby app that is very heavily based on a fork of this theme, I found this could be achieved easily by adding  @pauliescanlon 's `gatsby-mdx-embed` package into the mix.

With that plugin added you can (for example) embed a YouTube video in a .mdx file by adding the following:

```
<YouTube youTubeId="2Gi9SRsRrE4"/>
```

I'll offer up a PR for your convenience, however not sure if this a direction you want to take - this is speculative!

**Comment by mathieudutour** [comment]
Because it's super easy to use `gatsby-mdx-embed` with the theme (you just have to add to to your gatsby-config), I'm not sure I want to add it by default. But what I want to figure out is a way to easily provide mdx components to the theme.

I'd be curious to know what you need to fork the theme for that can't be achieved by shadowing it.

**Comment by PaulieScanlon** [comment]
@mathieudutour I'd say if this is a theme don't provide `gatsby-mdx-embed` by default. As you say it can easily be added by the theme user in `gatsby-config`

If you want to provide other components to the theme you can pass them in via the `MDXProvider` and use the `components` prop -> https://github.com/PaulieScanlon/gatsby-theme-terminal/blob/master/%40pauliescanlon/gatsby-theme-terminal/src/components/Main/Main.js#L168

In my theme `gatsby-theme-terminal` i provide all the default Theme UI components -> https://gatsby-theme-terminal.netlify.app/theme-ui-components/

...and a set of custom "data" components -> https://gatsby-theme-terminal.netlify.app/components/ 

It's how i made all the data viz on my blog https://paulie.dev/dashboard/

**Comment by mathieudutour** [comment]
yeah, I mean how the user of the theme can point to a folder of their mdx components without any other config. But maybe it should just be an option of the theme

**Comment by PaulieScanlon** [comment]
@mathieudutour ah i see, yeah i think you'll need to expose the MDXProvider or a Main file and that can then be shadowed. Although i'd wonder if this is beyond the scope of a theme. Some of what you provide the user with in the theme is kinda locked down... that's what i think themes are anyway. If they want full control then perhaps a theme isn't the right way to go.

**Comment by synesthesia** [comment]
OK @mathieudutour that's me showing my very limited Gatsby knowledge. 

I couldn't see how you would inject the plugin at the right place with just shadowing, hence the more complex approach.  Gatsby docs talk about shadowing components and CSS but not plugins - learning curve is v steep even though this is not the first time I've played with Gatsby. Is it just a case of adding it to `plugins` in `gatsby-config.js` before the dependency on `gatsby-theme-garden`? (Sorry I know you're not here to be my Gatsby coach!)

The deeper I dig mdx does seem to be more complex. Apart from completions not working in Markdown Notes - which is for another place and which I could probably live with in the short term, I'm seeing odd behaviour on the processing of wikilinks in the rendered webpage built with yor theme - with default stripBrackets:false set on gatsby-remark-double-brackets-link I see a single bracket around a wikilink on a [web page built from normal md](https://pedantic-austin-af604a.netlify.app/federated-wiki), but a double bracket on a [page built from mdx](https://pedantic-austin-af604a.netlify.app/federated-wiki-knowledge-cycle)

**Comment by mathieudutour** [comment]
> Is it just a case of adding it to plugins in gatsby-config.js before the dependency on gatsby-theme-garden?

Yes, a gatsby theme is just like a gatsby plugin. You can use as many as you want at the same time.

>  I'm seeing odd behaviour on the processing of wikilinks in the rendered webpage built with yor theme - with default stripBrackets:false set on gatsby-remark-double-brackets-link I see a single bracket around a wikilink on a web page built from normal md, but a double bracket on a page built from mdx

That might be a bug. Could you provide an example page with the config you are using? I'll try to reproduce.

**Comment by synesthesia** [comment]
Thanks @mathieudutour will stick together another site that uses your theme directly instead of copying the source.

The examples linked in my previous comment show the result, but they are produced by the monstrosity I have hacked together. Let me put together a different build that correctly just includes your theme and the embed plugin and will send you new links etc.

**Comment by mathieudutour** [comment]
I couldn't access the notes to see why it's like that :)

**Comment by synesthesia** [comment]
ah OK @mathieudutour you need notes source too?

**Comment by mathieudutour** [comment]
Yeah to see why the links aren't rendering properly: how they are written, what they are pointing to, etc.

**Comment by synesthesia** [comment]
ok will put together a test repo

**Comment by synesthesia** [comment]
Test repo ready and published @mathieudutour .

Publishing code is [here](https://github.com/synesthesia/foam-tester-build)

Source Foam is [here](https://github.com/synesthesia/foam-tester-source)

Example of a normal page is [here](https://pedantic-austin-af604a.netlify.app/a-normal-page)

Example of a page built from mdx is [here](https://pedantic-austin-af604a.netlify.app/an-mdx-page)

They are exhibiting subtly different behaviour:

* on a page built from `.md` wikilinks to other `.md` pages have single brackets, but links to pages built from `.mdx` have a double bracket
* on a page built from `.mdx` links to "normal" pages also have a double bracket.

Looking at the source markdown [here](https://raw.githubusercontent.com/synesthesia/foam-tester-source/master/a-normal-page.md) and [here](https://raw.githubusercontent.com/synesthesia/foam-tester-source/master/an-mdx-page.mdx) I think this is because Foam is inserting the link references for links to normal pages that appear on normal pages, but ignores links to `.mdx` pages from normal pages, and does nothing at all on `.mdx` pages. 

So not a bug with your theme at all. :-)

Lastly, prompted by something @jevakallio mentioned over in Discord, I've added a normal `.md` page with an embedded resource - [which works absolutely fine in publishing terms](https://pedantic-austin-af604a.netlify.app/a-normal-note-with-embedded-resource)
