### ISSUE TITLE
How to add syntax highlighting support?

### ISSUE THREAD

**Issue by thisizkp** [mathieudutour/gatsby-digital-garden#37]
Hey, @mathieudutour thanks for the project.

It works pretty well. I wanted to add syntax highlighting for my code snippets. Would love to use something like this plugin - https://github.com/andrewbranch/gatsby-remark-vscode. But it seems like I can't really pass options to the config. Is it possible to do this in any other way?

**Comment by mathieudutour** [comment]
Another way would be to use a react component like in this example: https://github.com/mdx-js/mdx/tree/master/examples/syntax-highlighting

To inject your component into the mdx renderer:
- create a file with your react component (something like https://github.com/mdx-js/mdx/blob/master/examples/syntax-highlighting/src/components/CodeBlock.js)
- create a file named `./src/gatsby-theme-garden/components/mdx-components/index.js` with the following content
    ```js
    // the components provided by the theme
    export { AnchorTag as a } from "gatsby-theme-garden/src/components/mdx-components/anchor-tag";

    // your own component to inject into mdx
    export code from "./your-component"; // any code block with use this component
    ```

I need to write proper documentation about this (or I'd be happy to accept a PR 😄)

**Comment by thisizkp** [comment]
@mathieudutour thanks 👍 

Would be happy to write documentation for the above and raise a PR. But I didn't see any existing docs for the project. Where should the docs go? Is README fine?

**Comment by mathieudutour** [comment]
yeah there are some docs in the readme here: https://github.com/mathieudutour/gatsby-digital-garden/tree/master/packages/gatsby-theme-garden
