### ISSUE TITLE
Linked notes do not stack any more

### ISSUE THREAD

**Issue by keikhcheung** [mathieudutour/gatsby-digital-garden#38]
Opening linked notes used to make extra panes to the right and stack them on the origin notes. But since the latest update, it opens directly the specific target note pages, instead of creating a stack.

**Comment by thisizkp** [comment]
@keikhcheung I'm able to open the linked notes in a stacked manner. 

I am not able to reproduce the issue. Can you please mention more steps to reproduce?

**Comment by keikhcheung** [comment]
I tried digging into it but unfortunately I cannot figure out why specifically… In the end I reverted to a backup from end of July and reloaded it with new content. It's now working fine again. I suppose it was perhaps owing to some clashes / incompatibility issues with other dependent Gatsby modules.

Thanks for reaching out @thisizkp though. 🙂

**Comment by micahchoo** [comment]
Linked notes don't stack for me either when I click it through the text but they kinda work when I navigate through the graph
