### ISSUE TITLE
Bug? Private pages logic inverted?

### ISSUE THREAD

**Issue by synesthesia** [mathieudutour/gatsby-digital-garden#40]
Hi @mathieudutour thanks for adding the private pages feature in dbf6d1c44c075

However I wonder if the logic is inverted? (appreciate I don’t know the thinking behind the change)

To hide a page the frontmatter has to be `private: false` to not be selected in [gatsby-node.js L188](https://github.com/mathieudutour/gatsby-digital-garden/blob/master/packages/gatsby-theme-garden/gatsby-node.js#L188)

IMHO should be `private:true` to hide?

**Comment by mathieudutour** [comment]
Oh right silly me

**Comment by mathieudutour** [comment]
fixed in https://github.com/mathieudutour/gatsby-digital-garden/commit/3a91ce87c8e618725d1f059739b6033459902f76
