### ISSUE TITLE
Handle math expression

### ISSUE THREAD

**Issue by 101scholar** [mathieudutour/gatsby-digital-garden#41]
There are some simple math expressions like `$a^2$` for inline math or `$$\begin{aligned}x &= 2\\ &= 1 + 1\end{aligned}$$` for block math in my markdown file. Is it possible to render them properly? It seems that `gatsby-remark-mathjax` is an option. However, I am not familiar with the gatsby stuff and failed to configure it to work. Could you give a short tutorial in README or embed it in `gatsby-digtal-garden`?

**Comment by AndrewNatoli** [comment]
Hey @101scholar - I see you noticed the `gatsby-remark-mathjax` plugin.

Since it's a remark plugin and this theme uses mdx, it would get configured a little differently (if it can work at all-- I'm not sure).

So, there's this spot in the Gatsby docs that talks about using a remark plugin with mdx:
https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/#remark-plugins

In this repo if you peek at `packages/gatsby-theme-garden/gatsby-config.js` you'll find `gatsby-plugin-mdx` which has the `gatsbyRemarkPlugins` section you'll need to register the mathjax plugin in.

Hopefully that points you toward the right direction :D

**Comment by mathieudutour** [comment]
another way would be to use a Mdx component as discussed here: https://github.com/mathieudutour/gatsby-digital-garden/issues/37#issuecomment-670956136

**Comment by 101scholar** [comment]
Thx! I've tried `gatsby-remark-mathjax` and `gatsby-remark-ketax`. It didn't work and I think maybe plugins are not compatible or maybe I've made some silly beginner's mistakes. Instead I found the following configuration (added in `gatsby-config.js`) does work:

```javascript
resolve: `gatsby-plugin-mdx`,
    options: {
        remarkPlugins: [require(`remark-math`)],
        rehypePlugins: [require(`rehype-katex`)]
}
```

**Comment by FloriF** [comment]
Hi @101scholar  - could you explain in a bit more detail what you did to get it to work (plugin, anything else you adjusted)?
I am trying my best, however I am not really familiar with gatsby. Anything I try does not render the math expressions and additionally, the [[wikilinks]] stop working.

**Comment by 101scholar** [comment]
@FloriF FYI, I add the following code in `gatsby-config.js`:

```javascript
module.exports = {
  plugins: [
    ...
    {
      resolve: `gatsby-plugin-mdx`,
        options: {
          remarkPlugins: [require(`remark-math`)],
          rehypePlugins: [require(`rehype-katex`)],
          extensions: [`.md`, `.mdx`],
          gatsbyRemarkPlugins: [
            "gatsby-remark-double-brackets-link",
            "gatsby-remark-double-parenthesis-link",
            {
              resolve: `gatsby-remark-images`,
              options: {
                maxWidth: 561,
              },
            },
            `gatsby-remark-copy-linked-files`,
            {
              resolve: `gatsby-remark-autolink-headers`,
              options: {
                icon: false,
              },
            },
          ],
        }
    }
  ],
}

```

where except for the two lines of

```javascript
remarkPlugins: [require(`remark-math`)],
rehypePlugins: [require(`rehype-katex`)],
```

others are just the default  `gatsby-plugin-mdx` related config copied from `node_modules/gatsby-theme-garden/gatsby-config.js`.

**Comment by Stvad** [comment]
important note: you want to use versions 3* of both plugins with gatsby

**Comment by lqhl** [comment]
`remark-math` and `rehype-katex` don't work properly (I installed version 3* `npm install --save remark-math@~3 rehype-katex@~3`). Can someone update this solution?
