### ISSUE TITLE
Configuring titleToUrl option in double-brackets-link to accept different values

### ISSUE THREAD

**Issue by bathrobe** [mathieudutour/gatsby-digital-garden#47]
(I imagine this applies to the double parentheses plugin too)

In the gatsby-config for a site with the double-brackets-link plugin:
```js
{
  resolve: `gatsby-plugin-mdx`,
  options: {
    gatsbyRemarkPlugins: [
      {
        resolve: `gatsby-remark-double-brackets-link`,
        options: {
        titleToUrl: (here)
      },
    ],
  },
}
```
The titleToUrl option is supposed to be passed a function `(title: string) => `/${slugify(title)}`;` but Gatsby does not accept functions as config option values.
"Note that plugin options will be stringified by Gatsby, so they cannot be functions," from their [website](https://www.gatsbyjs.com/docs/using-a-plugin-in-your-site/).

For instance, I want my wikilink-generated notes to go to `root.com/notes/mynote`, where the note is lowercased. This would mean changing the titleToUrl function to `title => `/notes/${slugify(title), {lower: true}}`.

**Comment by mathieudutour** [comment]
should be fixed by https://github.com/mathieudutour/gatsby-digital-garden/commit/f0b555bb740733351440c3cd494fb37b3258462d
