### ISSUE TITLE
Errors linking to and from files nested in folders.

### ISSUE THREAD

**Issue by Am3ra** [mathieudutour/gatsby-digital-garden#49]
Using the foam template, as well as the extensions, there is a folder called Daily Notes. I have also made other personal folders. 

Liking to notes inside those folders from the base path causes problems of not linking correctly.
Linking to notes in the base path from inside a folder doesn't work correctly either.

I believe this problem could be caused by relative links, as the paths linking is relative to the current note, not to the base path. I'm not sure.

**Comment by Am3ra** [comment]
Steps to reproduce 

Install theme on new folder
`gatsby new my-digital-garden https://github.com/mathieudutour/gatsby-starter-digital-garden`

run locally
```
cd my-digital-garden
gatsby develop
```

click on the `[[hi]]` link (Link not found)

**Comment by oridov** [comment]
I get the same error. Just following the two steps from `README.md` and then clicking on `[[Hi]]' results in 404

**Comment by nathangathright** [comment]
After a fresh run through the quick-start guide, I was only able to successfully click on the `[[hi]]` link by pointing the `gatsby-theme-garden` entry in `package.json` to version `0.1.42` or older.

**Comment by Maybach91** [comment]
> After a fresh run through the quick-start guide, I was only able to successfully click on the `[[hi]]` link by pointing the `gatsby-theme-garden` entry in `package.json` to version `0.1.42` or older.
↳ Pointing it to `0.1.55` doesn’t solve the problem for me. Still not possible to link. It looks like its handling it as an external link. (and only shows the url/slug as hover)

Linking within the Graph is working tho. I’m not sure how to debug this, so i hope @mathieudutour will take a look into it, when he has time for it. :)

**Comment by hikerpig** [comment]
I tweaked the theme config in my fork of foam-gatsby-template by adding the `titleToURLPath` option to 'gatsby-remark-double-brackets-link' plugin.

But sadly this option will not be passed down by 'gatsby-theme-garden' so I will have to set `mdxOtherwiseConfigured: true` and copy all the plugins to the config. 

[See the diff here](https://github.com/mathieudutour/foam-gatsby-template/commit/ff59310dac9b13960ee4f72340548447b00db316#diff-74c94df4279710813e8cdfcd4d2e8b0ba23d02c45847662ca0dcdbdfa0a0f698R33)

@mathieudutour  Would you consider adding one extra option (something like `bracketsLinkOptions` e.g.), so the tweaking to support Foam project will not be so messy?

I'm not familiar with other plugins in this repo so my solution may not be the best. Anyway, thank you for your work here.

**Comment by mathieudutour** [comment]
Yeah happy for a new option.

Do you think your `titleToURL` should become the default?
I'm not sure why it shouldn't.

(Sorry I don't have much time to spend on this those days)

**Comment by hikerpig** [comment]
@mathieudutour That will do. Seems like you don't have ongoing plans for other solutions, I will open a PR for this 😃.

**Comment by hgcl** [comment]
Hi @mathieudutour! Do we have any updates regarding this open PR 👆? Just to know if it is planned to be merged or not. Thank you for the great project!
