### ISSUE TITLE
Search does not exclude "private" notes

### ISSUE THREAD

**Issue by AndrewNatoli** [mathieudutour/gatsby-digital-garden#71]
**Problem**

Notes with `private: true` denoted in their frontmatter have search results generated for them.

**Expected behavior**

Similar to how `gatsby-node` excludes page generation for notes with `private: true` in their frontmatter, the search indexes should be generated with this consideration if possible.

So if you create a note that looks like

```
---
private: true
---

Hello this is a note!
```

Then you search for "Hello this is a note" - You shouldn't see that note appear in the results. 

:D

**Comment by mathieudutour** [comment]
should be fixed in the new version
