### ISSUE TITLE
Process to get files from Roam

### ISSUE THREAD

**Issue by santiyounger** [mathieudutour/gatsby-digital-garden#92]
This looks amazing, thank you so much for sharing this amazing projects.

I already followed the instructions in the README and managed to make things run properly in a local host.

What do you recommend is the best way to bring files from Roam Research. Is there any other particular package with detailed instructions that you'd recommend.

I'd just love a bit of documentation, but I also understand that it's hard to create super detailed docs. And I'm already super greatful for the amazing project you've put out. So in general I'd just love to be pointed in the right direction

Thanks a lot!

**Comment by Stvad** [comment]
see a discussion in #84 for a few options for automatically fetching data

**Comment by santiyounger** [comment]
thanks I'll try those suggestions out
