### ISSUE TITLE
Support "draft: true"

### ISSUE THREAD

**Issue by hukacode** [mathieudutour/gatsby-digital-garden#93]
Hello,

I know you've already support "private: true" in front matter. 
Could you consider to support "draft: true"?

My usecase is just for compatible with existed Hugo files.

Best regards,
Huka

**Comment by mathieudutour** [comment]
Happy to accept a PR to support it yeah

**Comment by mathieudutour** [comment]
fixed in gatsby-theme-garden@0.1.64
